/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package itibu;

public class App {
    public String getGreeting() {
        return "Hello World!desu";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
